export const listTipeData = [
  {
    provider: "AXIS",
    tipe: ["Umum", "Bronet", "Mini", "Kzl", "Owsem", "Ekstra"],
  },
  {
    provider: "by.U",
    tipe: ["Umum", "Tiktok", "Kaget"],
  },
  {
    provider: "INDOSAT",
    tipe: [
      "Umum",
      "Ekstra",
      "Freedom Apps",
      "Freedom Combo",
      "Freedom Internet",
      "Freedom Longlife",
      "Freedom U",
      "Gift Data",
      "Haji",
      "Mini",
      "Yellow",
    ],
  },
  {
    provider: "SMARTFREN",
    tipe: [
      "Umum",
      "Gokil Max",
      "Nonstop",
      "Unlimited",
      "Unlimited Nonstop",
      "Volume",
    ],
  },
  {
    provider: "TELKOMSEL",
    tipe: [
      "Umum",
      "Bulk",
      "Combo Sakti",
      "Flash",
      "Facebook",
      "GigaMAX",
      "Instagram",
      "Ketengan TikTok",
      "Malam",
      "Maxstream",
      "OMG",
      "Orbit",
      "Whatsapp",
      "Youtube",
    ],
  },
  
  {
    provider: "TRI",
    tipe: [
      "Umum",
      "Addon",
      "AlwaysOn",
      "Cicilan",
      "GetMore",
      "Happy",
      "Home",
      "Mini",
      "Mix",
    ],
  },
  {
    provider: "XL",
    tipe: [
      "Umum",
      "Blue",
      "Conference",
      "Edukasi",
      "Hotrod",
      "Hotrod Special",
      "Mini",
      "Paket Akrab",
      "Xtra Kuota",
      "Xtra Combo Plus",
      "Xtra Combo",
      "Xtra Combo Flex",
      "Xtra On",
    ],
  },
];
